[project]
name = "mcp-client-basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.40.0",
    "fastmcp>=2.10.6",
    "mcp>=1.1.1",
    "openai>=1.97.1",
    "python-dotenv>=1.0.1",
]
